WCS\CoavBundle\Entity\Flight:
    type: entity
    table: null
    repositoryClass: WCS\CoavBundle\Repository\FlightRepository

    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO

    fields:
        pilot:
            type: string
            length: 255
        freeSeats:
            type: integer
            nullable: true
        takeoffTime:
            type: datetime
    lifecycleCallbacks: {  }

    manyToOne:
        departure:
            targetEntity: WCS\CoavBundle\Entity\Terrain
            inversedBy: departures

    manyToOne:
        arrival:
            targetEntity: WCS\CoavBundle\Entity\Terrain
            inversedBy: arrivals

    manyToOne:
        planeModel:
            targetEntity: WCS\CoavBundle\Entity\PlaneModel
